# This is a simple Makefile

# Compiler
#CC = gcc

# Compiler flags
CFLAGS =-Wall -g

# Source files
#SRC = ex1.c
#
# Object files
#OBJ = $(SRC:.c=.o)

# Executable name
#TARGET = ex1 ex3

# Default target
#all: $(TARGET)
##
all : ex1 ex3
# Linking the object files to create the executable
#$(TARGET): $(OBJ)
#	$(CC) $(CFLAGS) -o $@ $^

# Compiling each source file into an object file
#%.o: %.c
#	$(CC) $(CFLAGS) -c $< -o $@

# Clean up intermediate and executable files
clean:
#   rm -f $(OBJ) $(TARGET)
	rm -f ex1 ex3